### ISSUE TITLE
You need chromedriver to update..

### ISSUE THREAD

**Issue by rludva** [gantrior/solarwinds-meetup-workshop#3]
**After npm install I have to use 
_$ ./node_modules/protractor/bin/webdriver-manager update_ 
to update and download chromedriver.. (on fedora 23 system..). After this command tests are executed..**

/var/egit/gantrior/solarwinds-meetup-workshop$ npm test

> meetupdemo@1.0.0 test /var/egit/gantrior/solarwinds-meetup-workshop
> node node_modules/protractor/bin/protractor

[22:51:18] I/direct - Using ChromeDriver directly...
[22:51:18] I/launcher - Running 1 instances of WebDriver
[22:51:18] E/launcher - Error: Error: Could not find chromedriver at /var/egit/gantrior/solarwinds-meetup-workshop/node_modules/protractor/selenium/chromedriver_2.21
    at Direct.getNewDriver (/var/egit/gantrior/solarwinds-meetup-workshop/node_modules/protractor/built/driverProviders/direct.js:62:27)
    at Runner.createBrowser (/var/egit/gantrior/solarwinds-meetup-workshop/node_modules/protractor/built/runner.js:182:43)
    at /var/egit/gantrior/solarwinds-meetup-workshop/node_modules/protractor/built/runner.js:255:30
    at _fulfilled (/var/egit/gantrior/solarwinds-meetup-workshop/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/var/egit/gantrior/solarwinds-meetup-workshop/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/var/egit/gantrior/solarwinds-meetup-workshop/node_modules/protractor/node_modules/q/q.js:796:13)
    at /var/egit/gantrior/solarwinds-meetup-workshop/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/var/egit/gantrior/solarwinds-meetup-workshop/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/var/egit/gantrior/solarwinds-meetup-workshop/node_modules/protractor/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
[22:51:18] E/launcher - Process exited with error code 100
npm ERR! Test failed.  See above for more details.

**Comment by gantrior** [comment]
`npm run init` should cover that as it execute following command: `npm install && node node_modules/protractor/bin/webdriver-manager update && gulp tscompile`. 

Did you run `npm run init`?

**Comment by rludva** [comment]
Ouh, sorry I did not..
Yes it's ok, my mistak..
